name: pemrograman_mobile
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Export PDF
  pdf: ^3.11.0
  printing: ^5.13.4
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.4"


flutter:
  uses-material-design: true
  # assets:
  #   - assets/
  assets:
    - assets/images/ 

flutter_native_splash:
  color: "#FFFFFF"              # warna latar (hex)
  image: assets/images/group1.png # <-- UBAH INI (tanpa spasi)
  # (opsional) dark mode
  color_dark: "#121212"
  image_dark: assets/images/splash.png

  # Android 12 butuh icon bergaya "monochrome" (optional tapi bagus)
  android_12:
    color: "#FFFFFF"
    image: assets/images/splash.png # <-- pastikan file ini juga ada
    icon_background_color: "#FFFFFF"

  # (opsional) web/ios tweaks
  android: true
  ios: true
  web: true
